trigger:
- master

jobs:

- job: 'Test'
  strategy:
    matrix:
      Linux_Python36:
        imageName: 'ubuntu-latest'
        python.version: '3.6'
      Linux_Python39:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      MacOS_Python36:
        imageName: 'macos-latest'
        python.version: '3.6'
      MacOS_Python39:
        imageName: 'macos-latest'
        python.version: '3.9'
      Windows_Python36:
        imageName: 'windows-latest'
        python.version: '3.6'
      Windows_Python39:
        imageName: 'windows-latest'
        python.version: '3.9'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install .[celery,redis,dev]
    displayName: 'Install dependencies'

  - script: |
      python setup.py lint
    displayName: 'Run lint tests'

  - script: |
      python setup.py test
    displayName: 'Run pytest tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
